databaseType = "PostgreSql"
id = "967fb1ab-84c1-4f0f-bef0-9a41d9e61a6e"
name = "chronicle"

[flyway]
callbackLocations = [ "filesystem:callbacks" ]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
enableMigrations = true
developmentEnvironment = "development"
shadowEnvironment = "shadow"

  [flywayDesktop.generate]
  undoScripts = false

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.postgresql.options.behavior]
detectRenames = "identical-only"

[redgateCompare.postgresql.options.ignores]
ignoreNewlinesInTextObjects = "off"
