spring.application.name=chronicle

# web handling
spring.web.resources.add-mappings=false

# import .env file
spring.config.import=optional:file:./.env[.properties]

# database variables
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# hibernate setup
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# enable flyway
spring.flyway.enabled=true
spring.flyway.clean-disabled=false